version: '2.0'

volumes:
  gopkg:

networks:
  shared:
    external: true

services:
  proxy:
    build: .
    image: juanwaj/dockerdev
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - shared
    ports:
      - 80:80
      - 443:443
      - 19322:19322/udp
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: '3'

  monitor:
    image: golang:1.6
    working_dir: /app
    command: sh -c 'go get -d -v && go build monitor.go'
    environment:
      GOPATH: /go
    volumes:
      - .:/app
      - gopkg:/go
